import {
    BODY_TYPES,
    COLORS,
    DRIVE_TYPES,
    FUEL_TYPES,
    POWERTRAIN_TYPES,
    CAR_STATUS,
    TRANSMISSION_TYPES,
} from "../../constants";

export const MAP_FILTERS = [
    {
        type: "checkbox",
        key: "status",
        field: "status",
        label: "Статус",
        items: CAR_STATUS,
    },
    {
        type: "range",
        key: "averageRating",
        label: "Рейтинг",
        min: 0,
        max: 5,
        step: 0.1,
        suffix: "★"
    },
    {
        type: "range",
        key: "pricePerDay",
        label: "Вартість за добу",
        min: 0,
        max: 20000,
        step: 100,
        suffix: "грн",
    },
    {
        type: "range",
        key: "year",
        label: "Рік випуску",
        min: 2000,
        max: new Date().getFullYear(),
        step: 1,
    },
    {
        type: "checkbox",
        key: "bodyType",
        field: "bodyType",
        label: "Тип кузова",
        items: BODY_TYPES,
    },
    {
        type: "checkbox",
        key: "transmissionType",
        field: "transmissionType",
        label: "Тип трансмісії",
        items: TRANSMISSION_TYPES,
    },
    {
        type: "checkbox",
        key: "driveType",
        field: "driveType",
        label: "Тип приводу",
        items: DRIVE_TYPES,
    },
    {
        type: "checkbox",
        key: "powertrainType",
        field: "powertrainType",
        label: "Тип силової установки",
        items: POWERTRAIN_TYPES,
    },
    {
        type: "checkbox",
        key: "fuelType",
        field: "engine.fuelType",
        label: "Тип палива",
        items: FUEL_TYPES,
    },
    {
        type: "range",
        key: "displacement",
        field: "engine.displacement",
        label: "Об'єм двигуна",
        min: 0,
        max: 10,
        step: 0.1,
        suffix: "л",
    },
    {
        type: "range",
        key: "capacity",
        field: "battery.capacity",
        label: "Ємність батареї",
        min: 1,
        max: 200,
        step: 1,
        suffix: "кВт·год",
    },
    {
        type: "range",
        key: "range",
        field: "battery.range",
        label: "Запас ходу",
        min: 1,
        max: 1000,
        step: 1,
        suffix: "км",
    },
    {
        type: "range",
        key: "seats",
        label: "Кількість місць",
        min: 1,
        max: 9,
        step: 1,
    },
    {
        type: "checkbox",
        key: "color",
        label: "Колір",
        field: "color",
        items: COLORS,
    },
];