import "./AppButton/AppButton.css";
import "./Footer/Footer.css";
import "./FormControllers/FormControllers.css";
import "./Forms/Forms.css";
import "./Header/Header.css";
import "./Loader/Loader.css";
import "./MessageDialog/MessageDialog.css";
import "./MonitoringMap/MonitoringMap.css";
import "./Tables/Tables.css";