export const USER = {
    HOME: "/",
    MAP: "/map",

    PROFILE: "/profile",
    PROFILE_DETAILS: "/profile/:id",
    PROFILE_EDIT: "/profile/:id/edit",
    profileDetails: (id) => `/profile/${id}`,
    profileEdit: (id) => `/profile/${id}/edit`,

    BOOKING_PERIOD: "/booking/:id/date",
    BOOKING_PAYMENT: "/booking/:id/payment",
    BOOKING_CONFIRM: "/booking/:id/confirm",
    BOOKING_HISTORY: "/booking/history",
    BOOKING_HISTORY_DETAILS: "/booking/history/:id",
    bookingPeriod: (id) => `/booking/${id}/date`,
    bookingPayment: (id) => `/booking/${id}/payment`,
    bookingConfirm: (id) => `/booking/${id}/confirm`,
    bookingHistoryDetails: (id) => `/booking/history/${id}`,

    TRIP_START: "/trip/:id/start",
    TRIP_ACCESS: "/trip/:id/access",
    TRIP_CONDITION_START: "/trip/:id/condition-start",
    TRIP_ACTIVE: "/trip/:id",
    TRIP_CONDITION_END: "/trip/:id/condition-end",
    TRIP_PAYMENT: "/trip/:id/payment",
    TRIP_SUMMARY: "/trip/:id/summary",
    TRIP_HISTORY: "/trip/history",
    TRIP_HISTORY_DETAILS: "/trip/history/:id",
    tripStart: (id) => `/trip/${id}/start`,
    tripAccess: (id) => `/trip/${id}/access`,
    tripConditionStart: (id) => `/trip/${id}/condition-start`,
    tripActive: (id) => `/trip/${id}`,
    tripConditionEnd: (id) => `/trip/${id}/condition-end`,
    tripPayment: (id) => `/trip/${id}/payment`,
    tripSummary: (id) => `/trip/${id}/summary`,
    tripHistoryDetails: (id) => `/trip/history/${id}`,
}