export const USER = {
    HOME: "/",
    MAP: "/map",

    PROFILE: "/profile",
    PROFILE_DETAILS: "/profile/:id",
    PROFILE_EDIT: "/profile/:id/edit",
    profileDetails: (id) => `/profile/${id}`,
    profileEdit: (id) => `/profile/${id}/edit`,

    BOOKING_PERIOD: "/bookings/:id/date",
    BOOKING_PAYMENT: "/bookings/:id/payment",
    BOOKING_CONFIRM: "/bookings/:id/confirm",
    BOOKINGS_HISTORY: "/bookings/history",
    BOOKINGS_HISTORY_DETAILS: "/bookings/history/:id",
    bookingPeriod: (id) => `/bookings/${id}/date`,
    bookingPayment: (id) => `/bookings/${id}/payment`,
    bookingConfirm: (id) => `/bookings/${id}/confirm`,
    bookingsHistoryDetails: (id) => `/bookings/history/${id}`,

    TRIP_START: "/trips/:tripId/start",
    TRIP_ACCESS: "/trips/:tripId/access",
    TRIP_CONDITION_START: "/trips/:tripId/condition-start",
    TRIP_ACTIVE: "/trips/:tripId",
    TRIP_CONDITION_END: "/trips/:tripId/condition-end",
    TRIP_SUMMARY: "/trips/:tripId/summary",
    TRIPS_HISTORY: "/trips/history",
    TRIPS_HISTORY_DETAILS: "/trips/history/:id",
    tripStart: (id) => `/trips/${id}/start`,
    tripAccess: (id) => `/trips/${id}/access`,
    tripConditionStart: (id) => `/trips/${id}/condition-start`,
    tripActive: (id) => `/trips/${id}`,
    tripConditionEnd: (id) => `/trips/${id}/condition-end`,
    tripSummary: (id) => `/trips/${id}/summary`,
    tripsHistoryDetails: (id) => `/trips/history/${id}`,
}