export const CAR_FORM_DEFAULT_VALUES = {
    images: [],
    status: "",
    brand: "",
    model: "",
    year: "",
    licensePlate: "",
    transmissionType: "",
    mileage: "",
    pricePerDay: "",
    powertrainType: "",
    displacement: "",
    fuelType: "",
    capacity: "",
    range: "",
    bodyType: "",
    driveType: "",
    color: "",
    seats: "",
    latitude: "",
    longitude: ""
}